server:
   #address: localhost
   port: 8089
   servlet:
       context-path: /uniro-api/ # Context path of the application.
       display-name: UniroApi # Display name of the application.

#Local DB
mongo:
    db:
     name: uniro
     host: localhost
     port: 27017
     u:
        key: 
     p:
        value: 

uniro:
   token:
      header: X-Auth-Token
      secret: prsm! 
      expiration: 72000
      inactivity:
              time: 72000
   auth:
     header: X-AUTH-HEADER
   secret:
       key: admin
   media:
      location: /as/a/s
      url: /abc/xyz
      temp : /tmp/	    

#Multipart      
spring:
  servlet:
    multipart:
      max-file-size: 100MB 
      max-request-size: 100MB    
      #location: /tmp/   
      
management:
       endpoints:
             enabled-by-default: true
             web:
               base-path: /actuator
               path-mapping.health: health 
               exposure:
                    include: "*"
                    exclude: env
             beans:
                 id: springbeans
                 sensitive: false
                 enabled: true 
       endpoint:
           health:
               enabled: true
               show-details: ALWAYS
           shutdown:
               enabled: true
           info:
              app: 
                name: Uniro Rest-API Application
                description: This application provides IOT Data for large Transports Companies
                version: 1.0.0
              enabled: true
